name: CI

on:
  push:
    branches: [main]

jobs:
  Deploy-Github-Actions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Unit Test
        run: yarn test

      - name: Build
        env:
          SKIP_PREFLIGHT_CHECK: true
        run: yarn build

      - name: Archive test results
        uses: actions/upload-artifact@v1
        with:
          name: test-report
          path: reports/test

      - name: Archive linter
        uses: actions/upload-artifact@v1
        with:
          name: lint-report
          path: reports/eslint.html

      - name: Archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: coverage-report
          path: reports/coverage

